graph TB
    subgraph C4["C4: Nivel 2 - Diagrama de Contenedores PrevySeg"]
        USER["Usuarios Web: Alumnos, Docentes, Admins"] -->|HTTPS / TLS 1.3| SPA["Single Page Application: React 19 + Vite + Tailwind v4"]
        SPA -->|REST / PostgREST| API_REST["Supabase PostgREST API Gateway"]
        SPA -->|Auth JWT & Bcrypt| AUTH_SVC["Supabase GoTrue Auth Service"]
        SPA -->|WebSockets WSS| RT_SVC["Supabase Realtime Engine"]
        
        API_REST -->|SQL con Row Level Security| DB[("PostgreSQL 15 Cluster + pgcrypto")]
        AUTH_SVC -->|Stored Procedures Bcrypt| DB
        SPA -->|HTTPS Webhook| WA["WhatsApp Business API"]
        SPA -->|Redirect / Token| WEBPAY["Pasarela Webpay Plus Transbank"]
    end
